export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS_SUCCESS = 'RECEIVE_QUESTIONS_SUCCESS';
export const RECEIVE_QUESTIONS_FAILED = 'RECEIVE_QUESTIONS_FAILED';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const ANSWERD_QUESTION = 'ANSWERD_QUESTION';
export const TIME_OUT = 'TIME_OUT';