export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS_SUCCESS = 'RECEIVE_QUESTIONS_SUCCESS';
export const RECEIVE_QUESTIONS_FAILED = 'RECEIVE_QUESTIONS_FAILED';
export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN_SUCCESS = 'RECEIVE_TOKEN_SUCCESS';
export const RECEIVE_TOKEN_FAILED = 'RECEIVE_TOKEN_FAILED';
