export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS_SUCCESS = 'RECEIVE_QUESTIONS_SUCCESS';
export const RECEIVE_QUESTIONS_FAILED = 'RECEIVE_QUESTIONS_FAILED';


export const NEXT_QUESTION = 'NEXT_QUESTION';
export const ANSWERED_QUESTION = 'ANSWERED_QUESTION';
export const RESTART = 'RESTART';

export const STOP_TIME = 'STOP_TIME';
export const SET_TIME_VALUE = 'SET_TIME_VALUE';
export const SEND_TIME_ID = 'SEND_TIME_ID';
